# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"!\n\rClientRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"!\n\x0e\x43lientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x17\x43hatSubscriptionRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x12\n\nqueue_name\x18\x02 \x01(\t\"2\n\x0b\x43hatRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x12\n\nqueue_name\x18\x02 \x01(\t\"\x1f\n\x0c\x43hatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1b\n\x08\x43hatInfo\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\"1\n\x10\x43hatListResponse\x12\x1d\n\x05\x63hats\x18\x01 \x03(\x0b\x32\x0e.chat.ChatInfo\"D\n\x0eMessageRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x13MessageListResponse\x12\x1f\n\x08messages\x18\x01 \x03(\x0b\x32\r.chat.Message\"?\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\x8d\x03\n\x0b\x43hatService\x12=\n\x0eRegisterClient\x12\x13.chat.ClientRequest\x1a\x14.chat.ClientResponse\"\x00\x12?\n\x10GetClientAddress\x12\x13.chat.ClientRequest\x1a\x14.chat.ClientResponse\"\x00\x12I\n\x12SubscribeGroupChat\x12\x1d.chat.ChatSubscriptionRequest\x1a\x12.chat.ChatResponse\"\x00\x12\x36\n\rDiscoverChats\x12\x0b.chat.Empty\x1a\x16.chat.ChatListResponse\"\x00\x12<\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\"\x00\x12=\n\x0bGetMessages\x12\x11.chat.ChatRequest\x1a\x19.chat.MessageListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTREQUEST']._serialized_start=20
  _globals['_CLIENTREQUEST']._serialized_end=53
  _globals['_CLIENTRESPONSE']._serialized_start=55
  _globals['_CLIENTRESPONSE']._serialized_end=88
  _globals['_CHATSUBSCRIPTIONREQUEST']._serialized_start=90
  _globals['_CHATSUBSCRIPTIONREQUEST']._serialized_end=152
  _globals['_CHATREQUEST']._serialized_start=154
  _globals['_CHATREQUEST']._serialized_end=204
  _globals['_CHATRESPONSE']._serialized_start=206
  _globals['_CHATRESPONSE']._serialized_end=237
  _globals['_EMPTY']._serialized_start=239
  _globals['_EMPTY']._serialized_end=246
  _globals['_CHATINFO']._serialized_start=248
  _globals['_CHATINFO']._serialized_end=275
  _globals['_CHATLISTRESPONSE']._serialized_start=277
  _globals['_CHATLISTRESPONSE']._serialized_end=326
  _globals['_MESSAGEREQUEST']._serialized_start=328
  _globals['_MESSAGEREQUEST']._serialized_end=396
  _globals['_MESSAGERESPONSE']._serialized_start=398
  _globals['_MESSAGERESPONSE']._serialized_end=432
  _globals['_MESSAGELISTRESPONSE']._serialized_start=434
  _globals['_MESSAGELISTRESPONSE']._serialized_end=488
  _globals['_MESSAGE']._serialized_start=490
  _globals['_MESSAGE']._serialized_end=553
  _globals['_CHATSERVICE']._serialized_start=556
  _globals['_CHATSERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
