# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_unificado_pb2 as chat__unificado__pb2


class ChatServiceStub(object):
    """Definiciones para el servicio de chat unificado (grupal y privado)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/chat.ChatService/RegisterClient',
                request_serializer=chat__unificado__pb2.ClientRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.ClientResponse.FromString,
                )
        self.GetClientAddress = channel.unary_unary(
                '/chat.ChatService/GetClientAddress',
                request_serializer=chat__unificado__pb2.ClientRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.ClientResponse.FromString,
                )
        self.SubscribeGroupChat = channel.unary_unary(
                '/chat.ChatService/SubscribeGroupChat',
                request_serializer=chat__unificado__pb2.ChatSubscriptionRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.ChatResponse.FromString,
                )
        self.DiscoverChats = channel.unary_unary(
                '/chat.ChatService/DiscoverChats',
                request_serializer=chat__unificado__pb2.Empty.SerializeToString,
                response_deserializer=chat__unificado__pb2.ChatListResponse.FromString,
                )
        self.ListUsers = channel.unary_unary(
                '/chat.ChatService/ListUsers',
                request_serializer=chat__unificado__pb2.Empty.SerializeToString,
                response_deserializer=chat__unificado__pb2.UserListResponse.FromString,
                )
        self.EstablishConnection = channel.unary_unary(
                '/chat.ChatService/EstablishConnection',
                request_serializer=chat__unificado__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.ConnectionResponse.FromString,
                )
        self.SendMessageToUser = channel.unary_unary(
                '/chat.ChatService/SendMessageToUser',
                request_serializer=chat__unificado__pb2.PrivateMessageRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.PrivateMessageResponse.FromString,
                )
        self.ReceiveMessagesFromUser = channel.unary_stream(
                '/chat.ChatService/ReceiveMessagesFromUser',
                request_serializer=chat__unificado__pb2.Empty.SerializeToString,
                response_deserializer=chat__unificado__pb2.PrivateMessageResponse.FromString,
                )
        self.RegisterUser = channel.unary_unary(
                '/chat.ChatService/RegisterUser',
                request_serializer=chat__unificado__pb2.UserRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.Response.FromString,
                )
        self.GetUserPort = channel.unary_unary(
                '/chat.ChatService/GetUserPort',
                request_serializer=chat__unificado__pb2.UserRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.UserResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/chat.ChatService/SendMessage',
                request_serializer=chat__unificado__pb2.DirectMessageRequest.SerializeToString,
                response_deserializer=chat__unificado__pb2.Response.FromString,
                )


class ChatServiceServicer(object):
    """Definiciones para el servicio de chat unificado (grupal y privado)
    """

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeGroupChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstablishConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessageToUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessagesFromUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=chat__unificado__pb2.ClientRequest.FromString,
                    response_serializer=chat__unificado__pb2.ClientResponse.SerializeToString,
            ),
            'GetClientAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientAddress,
                    request_deserializer=chat__unificado__pb2.ClientRequest.FromString,
                    response_serializer=chat__unificado__pb2.ClientResponse.SerializeToString,
            ),
            'SubscribeGroupChat': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeGroupChat,
                    request_deserializer=chat__unificado__pb2.ChatSubscriptionRequest.FromString,
                    response_serializer=chat__unificado__pb2.ChatResponse.SerializeToString,
            ),
            'DiscoverChats': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverChats,
                    request_deserializer=chat__unificado__pb2.Empty.FromString,
                    response_serializer=chat__unificado__pb2.ChatListResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=chat__unificado__pb2.Empty.FromString,
                    response_serializer=chat__unificado__pb2.UserListResponse.SerializeToString,
            ),
            'EstablishConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.EstablishConnection,
                    request_deserializer=chat__unificado__pb2.ConnectionRequest.FromString,
                    response_serializer=chat__unificado__pb2.ConnectionResponse.SerializeToString,
            ),
            'SendMessageToUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessageToUser,
                    request_deserializer=chat__unificado__pb2.PrivateMessageRequest.FromString,
                    response_serializer=chat__unificado__pb2.PrivateMessageResponse.SerializeToString,
            ),
            'ReceiveMessagesFromUser': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessagesFromUser,
                    request_deserializer=chat__unificado__pb2.Empty.FromString,
                    response_serializer=chat__unificado__pb2.PrivateMessageResponse.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=chat__unificado__pb2.UserRequest.FromString,
                    response_serializer=chat__unificado__pb2.Response.SerializeToString,
            ),
            'GetUserPort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPort,
                    request_deserializer=chat__unificado__pb2.UserRequest.FromString,
                    response_serializer=chat__unificado__pb2.UserResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat__unificado__pb2.DirectMessageRequest.FromString,
                    response_serializer=chat__unificado__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Definiciones para el servicio de chat unificado (grupal y privado)
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/RegisterClient',
            chat__unificado__pb2.ClientRequest.SerializeToString,
            chat__unificado__pb2.ClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/GetClientAddress',
            chat__unificado__pb2.ClientRequest.SerializeToString,
            chat__unificado__pb2.ClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeGroupChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/SubscribeGroupChat',
            chat__unificado__pb2.ChatSubscriptionRequest.SerializeToString,
            chat__unificado__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/DiscoverChats',
            chat__unificado__pb2.Empty.SerializeToString,
            chat__unificado__pb2.ChatListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/ListUsers',
            chat__unificado__pb2.Empty.SerializeToString,
            chat__unificado__pb2.UserListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EstablishConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/EstablishConnection',
            chat__unificado__pb2.ConnectionRequest.SerializeToString,
            chat__unificado__pb2.ConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessageToUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/SendMessageToUser',
            chat__unificado__pb2.PrivateMessageRequest.SerializeToString,
            chat__unificado__pb2.PrivateMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveMessagesFromUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.ChatService/ReceiveMessagesFromUser',
            chat__unificado__pb2.Empty.SerializeToString,
            chat__unificado__pb2.PrivateMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/RegisterUser',
            chat__unificado__pb2.UserRequest.SerializeToString,
            chat__unificado__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/GetUserPort',
            chat__unificado__pb2.UserRequest.SerializeToString,
            chat__unificado__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/SendMessage',
            chat__unificado__pb2.DirectMessageRequest.SerializeToString,
            chat__unificado__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
