# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private_chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12private_chat.proto\x12\x0cprivate_chat\">\n\x11\x43onnectionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x17\n\x0ftarget_username\x18\x02 \x01(\t\"%\n\x12\x43onnectionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"L\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x17\n\x0ftarget_username\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\x0fMessageResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x89\x02\n\x12PrivateChatService\x12Z\n\x13\x45stablishConnection\x12\x1f.private_chat.ConnectionRequest\x1a .private_chat.ConnectionResponse\"\x00\x12L\n\x0bSendMessage\x12\x1c.private_chat.MessageRequest\x1a\x1d.private_chat.MessageResponse\"\x00\x12I\n\x0fReceiveMessages\x12\x13.private_chat.Empty\x1a\x1d.private_chat.MessageResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'private_chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=36
  _globals['_CONNECTIONREQUEST']._serialized_end=98
  _globals['_CONNECTIONRESPONSE']._serialized_start=100
  _globals['_CONNECTIONRESPONSE']._serialized_end=137
  _globals['_MESSAGEREQUEST']._serialized_start=139
  _globals['_MESSAGEREQUEST']._serialized_end=215
  _globals['_MESSAGERESPONSE']._serialized_start=217
  _globals['_MESSAGERESPONSE']._serialized_end=269
  _globals['_EMPTY']._serialized_start=271
  _globals['_EMPTY']._serialized_end=278
  _globals['_PRIVATECHATSERVICE']._serialized_start=281
  _globals['_PRIVATECHATSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
